export const hostURL = process.env.MOONSHOT_API_URL || 'http://localhost:5000';
export const basePathSessions = '/v1/sessions';
export const basePathPromptTemplates = '/v1/prompt_templates';
export const basePathConnectors = '/v1/connectors';
export const basePathLLMEndpoints = '/v1/llm_endpoints';
export const basePathCookbooks = '/v1/cookbooks';
export const basePathContextStrategies = '/v1/context_strategies';
export const basePathRecipes = '/v1/recipes';
export const basePathBenchmarks = '/v1/benchmarks';
