export enum BenchmarkHomeViews {
  HOME,
  NEW_SESSION,
}

export enum BenchmarkNewSessionViews {
  PRIMARY_USE_CASE = 'PRIMARY_USE_CASE',
  ENDPOINTS_SELECTION = 'ENDPOINTS_SELECTION',
  NEW_ENDPOINT_FORM = 'NEW_ENDPOINT_FORM',
  EDIT_ENDPOINT_FORM = 'EDIT_ENDPOINT_FORM',
  COOKBOOKS_SELECTION = 'COOKBOOKS_SELECTION',
  CONFIGURE_ADDITIONAL_REQUIREMENTS = 'CONFIGURE_ADDITIONAL_REQUIREMENTS',
  BENCHMARK_RUN_FORM = 'BENCHMARK_RUN_FORM',
}
