export enum BenchmarkHomeViews {
  HOME,
  NEW_SESSION,
}

export enum BenchmarkNewSessionViews {
  PRIMARY_USE_CASE,
  TOPICS_SELECTION,
  RECOMMENDED_TESTS,
  ENDPOINTS_SELECTION,
  NEW_ENDPOINT_FORM,
  COOKBOOKS_SELECTION,
}
