export enum MainSectionViews {
  BENCHMARK_SUBMENU,
  REDTEAM_SUBMENU,
  UTILS_SUBMENU,
  QUICKSTART_HOME,
  REDTEAMING,
}

export enum RedTeamingViewSteps {
  SELECT_MODEL,
  CREATE_NEW_ENDPOINT,
  SESSION_DETAILS,
}
